def optimise_plan(user_plan: str):

    retrieved_docs = retrieve_docs(user_plan, k=3)
    prompt = build_prompt(user_plan, retrieved_docs)

    model = genai.GenerativeModel(MODEL_NAME)
    response = model.generate_content(prompt)

    if not response or not response.text:
        return {"raw_response": "No response generated by model."}

    raw_text = response.text

    try:
        return json.loads(raw_text)

    except Exception:
        start = raw_text.find("{")
        end = raw_text.rfind("}")

        if start != -1 and end != -1 and start < end:
            try:
                return json.loads(raw_text[start:end + 1])
            except Exception:
                pass

        return {"raw_response": raw_text}